apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnopconditionals.nop.example.org
spec:
  group: nop.example.org
  names:
    kind: XNopConditional
    plural: xnopconditionals
  versions:
  - name: v1alpha1
    referenceable: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              env:
                type: string
              render:
                type: boolean
              deployment:
                type: object
                properties:
                  blue:
                    description: Activate the blue resource
                    type: boolean
                  green:
                    description: Activate the green resource
                    type: boolean